Add rendered changes check
technekes/danger pull request #28
Opened 2021-05-25 18:54 UTC by ianyount

Raise an error and reject build if if rendering causes changes
Issue #24

2021-05-25 20:07 UTC, scookdev requested changes

2021-05-25 20:07 UTC, scookdev commented on incent-config/Dangerfile
> +  fail('Changes occoured while rendering')
Maybe provide a little more feedback here -

```sh
fail('Changes occurred while rendering - generate files from templates before pushing')
```

2021-05-26 16:02 UTC, johnny-five commented
I, @johnallen3d, have checked:

### Style/Standards/Process

* [ ] If there is commented out code that should be deleted
* [ ] That the change implements what was requested in the [ticket]()
* [ ] For adequate test coverage for changed lines or critical code paths

### Code Quality

* [ ] Do the classes follow [CodeClimate 7 Patterns to Refactor](http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/)
* [ ] If there are more idiomatic ways of using our frameworks/libraries
* [ ] Are there alternative implementations or refactors that increase readability/understandability and/or maintainability
* [ ] I can actually understand what the code is doing (if you're struggling to understand, then others may as well)
* [ ] This change is ready for production, if not should there should be a [feature flag](https://github.com/voormedia/flipflop)

### Security and Privacy

* [ ] Do the changes raise any security or privacy concerns

2021-05-26 17:01 UTC, johnallen3d approved these changes

2021-05-26 17:02 UTC, merged